openapi: 3.0.0
info:
  version: "1.0"
  title: "REST Notes API without Auth"
servers:
  - url: "https://example.com/Dev"
paths:
  /notes:
    post:
      responses:
        '201':
          description: "OK"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ ApiGatewayExecutionRole, Arn ]
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateNoteFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"

  /notes/{userId}:
    get:
      responses:
        '201':
          description: "OK"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ ApiGatewayExecutionRole, Arn ]
        type: "aws_proxy"
        httpMethod: "GET"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListUserNotesFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"


  /notes/{userId}/{noteId}:
    get:
      responses:
        '200':
          description: "User Note Found"
        # '404':
        #   description: "Note does not exist"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ ApiGatewayExecutionRole, Arn ]
        type: "aws_proxy"
        httpMethod: "GET"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUserNoteFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"
