openapi: 3.0.0
info:
  version: "1.0"
  title: "notes-api"
servers:
  - url: "https://example.com/Dev"
paths:
  /notes:
    post:
      responses:
        '201':
          description: "OK"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ ApiGatewayExecutionRole, Arn ]
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateNoteFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"
    get:
      responses:
        '200':
          description: "OK"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ ApiGatewayExecutionRole, Arn ]
        type: "aws_proxy"
        httpMethod: "GET"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getUserNoteFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"
